stages:
- name: Build Stage
  inputs:
  - type: git
    branch: stable
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
- name: Deploy Stage Filip
  inputs:
  - type: job
    stage: Build Stage
    job: Build
  triggers:
  - type: stage
  jobs:
  - name: Deploy to Stable
    type: deployer
    target:
      url: ${CF_TARGET_URL}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
      application: ${CF_APP}
    script: |-
      #!/bin/bash
      sleep 2m
      cf push "${CF_APP}"
      # View logs
      #cf logs "${CF_APP}" --recent
